# Generated by Django 3.2.23 on 2023-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('pymnt', models.CharField(choices=[('cash', 'Cash'), ('DC', 'Debit Card'), ('CC', 'Credit Card')], max_length=4)),
            ],
        ),
    ]
